name: Release tagged revision

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    # Use nuget restore instead of dotnet to support packages.config in Esatto.Win32.NetInjector.NetFx
    - name: Restore nuget
      run: nuget restore Esatto.Win32.sln
    - name: Build
      run: dotnet pack Esatto.Win32.sln -c Release -p PackageOutputPath=${{github.workspace}}/dist
    - name: NugetPush
      run: dotnet nuget push -s https://api.nuget.org/v3/index.json --api-key ${{secrets.MG_NUGET_SECRET}} --skip-duplicate "${{github.workspace}}/dist/**/*.nupkg"
    - name: Upload Release
      uses: ncipollo/release-action@v1.13.0
      with:
        artifacts: "dist/**/*"
