name: Release tagged revision

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Build Esatto.Win32.Com
      run: dotnet pack Esatto.Win32.Com -c Release -p:Version=${{github.ref_name}}
    - name: NugetPush Esatto.Win32.Com
      run: dotnet nuget push -s https://www.nuget.org/api/v2/package --api-key ${{secrets.MG_NUGET_SECRET}} Esatto.Win32.Com/bin/Release/Esatto.Win32.Com.${{github.ref_name}}.nupkg
    - name: Build Esatto.Win32.Common
      run: dotnet pack Esatto.Win32.Common -c Release -p:Version=${{github.ref_name}}
    - name: NugetPush Esatto.Win32.Common
      run: dotnet nuget push -s https://www.nuget.org/api/v2/package --api-key ${{secrets.MG_NUGET_SECRET}} Esatto.Win32.Common/bin/Release/Esatto.Win32.Common.${{github.ref_name}}.nupkg
    - name: Build Esatto.Win32.CommonControls
      run: dotnet pack Esatto.Win32.CommonControls -c Release -p:Version=${{github.ref_name}}
    - name: NugetPush Esatto.Win32.CommonControls
      run: dotnet nuget push -s https://www.nuget.org/api/v2/package --api-key ${{secrets.MG_NUGET_SECRET}} Esatto.Win32.CommonControls/bin/Release/Esatto.Win32.CommonControls.${{github.ref_name}}.nupkg
    - name: Build Esatto.Win32.Registry
      run: dotnet pack Esatto.Win32.Registry -c Release -p:Version=${{github.ref_name}}
    - name: NugetPush Esatto.Win32.Registry
      run: dotnet nuget push -s https://www.nuget.org/api/v2/package --api-key ${{secrets.MG_NUGET_SECRET}} Esatto.Win32.Registry/bin/Release/Esatto.Win32.Registry.${{github.ref_name}}.nupkg
